import Head from "next/head";
import "../styles/globals.css";
import Header from "../components/Header";
import { ThirdwebProvider } from "@thirdweb-dev/react";
function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ThirdwebProvider activeChain="localhost">
        <Header />
        <Component {...pageProps} />
      </ThirdwebProvider>
    </>
  );
}

export default MyApp;
